### ISSUE TITLE
Code / Updates?

### ISSUE THREAD

**Issue by Gandalf1783** [expanseElectronics/ethernetNodes#1]
Heyho,
couldn't help but notice that the Discordserver aswell as the production of the Ethernetnodes have stopped.

I was wondering if there are any updates to the node available and/or where the new place for the community is.

If the product is discontinued, I would love to see the source code, especially to update or tinker myself with the hardware.

Thanks!

**Comment by LoneWalkerWolf** [comment]
Hey!

All our products are listed on our website ([https://expanseelectronics.com](https://expanseelectronics.com)). We haven't stopped production of our ethernet nodes, but we are producing in batches, approximately ten units per quarter. 

We don't currently have a community system in place; however, if there is demand, we would be happy to recreate the Discord server. We decided to delete it previously due to spam-related issues. I am still very active in [The Green Room](https://discord.gg/thegreenroom) and via DM (LoneWalker#0556). 

Feel free to also reach out via email to me (alexander@expanseelectronics.com) or my colleague Matt Taylor (matt@expanseelectronics.com) with any further questions! :)

Best. 
Alex

**Comment by MicroMarty** [comment]
Hi,

Your project looks very interesting!

I tried to compile your code but I missed some library: ethEspDMX_RDM.h and ethEspArtNetRDM.h

But maybe I don't know where to look, can you help me?

Thanks!

**Comment by LoneWalkerWolf** [comment]
Hi @MicroMarty 

Ah, yes, that would be helpful to upload!
Both libraries are now in the root tree [found here.](https://github.com/expanseElectronics/ethernetNodes/tree/main/libraries)

Best, 
Alex

**Comment by MicroMarty** [comment]
Thanks a lot for your quick response, Alex!

**Comment by MicroMarty** [comment]
Hi,
Are you using a modified version of Ethernet Web server library ? 
I tried all version and a still get error regarding this library. 

Regards

**Comment by MicroMarty** [comment]
Hum I must be missing something...
I just create a new issue with the error.

**Comment by Gandalf1783** [comment]
Imma close this, thanks for answering Alex!
