### ISSUE TITLE
Build project using PlatformIO

### ISSUE THREAD

**Issue by mrv96** [expanseElectronics/ethernetNodes#6]
Since I saw some issue about project building, I've just published a *working* PlatformIO project of this repo: https://github.com/mrv96/ethernetNodes/tree/platformio

P.S.: *working* means that it builds successfully, I didn't tried it on field.

**Comment by LoneWalkerWolf** [comment]
Thanks for this! I'll give it a shot when I get a chance!

**Comment by spacyaldesign** [comment]
Hey Mrv96, 

thanks for your work. I could finally compile the code with plattform.io, but I cannot upload the code to the WT32-ETH01 because its showing this error: "A fatal error occurred: This chip is ESP32 not ESP8266. Wrong --chip argument?
*** [upload] Error 2"

It may be because its configured to run under ESP8266 Environment. Could you upload it already successful?

Regards!

**Comment by mrv96** [comment]
I think that this source code is for ESP8266 only. Probably it couldn't work on ESP32, which is the chip used on WT32-ETH0 board

________________________________

**Comment by LoneWalkerWolf** [comment]
Very late reply, and I apologise for this. 
The code is for ESP8266 only, we haven't found a need where the ESP32 is needed, feel free to rewrite the code / libraries to work with the ESP32 and its WT32-ETH0 board. 

The above board also uses a completely different ethernet controller, the LAN8720A. Our board and code use the W5500 ethernet IC.

**Comment by mrv96** [comment]
Finally I found the time to try PlatformIO project on hardware. After few attempts it worked! I updated my branch with the necessary fixes.

Further feedbacks are welcome!
